dist: xenial
matrix:
  include:
    - language: r
      r: 
        - 3.5
      sudo: required
      cache: packages
      before_install:
        - cd R
        - ls
      before_script:
        - sudo bash "../Travis-CI/installODBC.sh"
      script:
        - R CMD build .
        - travis_wait 30 R CMD check sqlmlutils_0.7.3.tar.gz --as-cran
