# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SERVER: ${{ secrets.SERVER }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PASSWORD_AIRLINE_USER: ${{ secrets.PASSWORD_AIRLINE_USER }}
  PASSWORD_AIRLINE_USER_DBOWNER: ${{ secrets.PASSWORD_AIRLINE_USER_DBOWNER }}
  DATABASE: ${{ secrets.DATABASE }}

jobs:
  R:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: [3.5]

    env:
      # Define CI to skip some test case.
      CI: True

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        working-directory: ./R
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        working-directory: ./R
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

  Python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    env:
      DRIVER: "{ODBC Driver 17 for SQL Server}"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install odbc driver
      working-directory: ./Python
      run: |
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
    - name: Install dependencies
      working-directory: ./Python
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8
    #   working-directory: ./Python
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run build script
      working-directory: ./Python
      run: ./buildandinstall.sh
    - name: Test with pytest
      working-directory: ./Python/tests
      run: |
        pytest